### PR TITLE
Added 3 slack params to global configuration :

### PR DESCRIPTION
**Pull request by mrik974**
- bot username
- bot icon  url
- bot icon emoji
These params are used for slack webhook enhancement.

### CODE REVIEW

**Comment by SuperTux88** [comment]
Hi @mrik974 

I've just seen this pull request. I did some refactorings to the settings-system in another pull-request (#32, not yet merged). I think it is easier to add your configs after this is merged, because it needs less code then.

Also please don't format the whole files, only touch the lines you have changed. You have replaced all spaces with tabs. This creates big diffs, "breaks" `git annotate` and creates more conflicts.

**Comment by mrik974** [comment]
Hi,

Thank you for your answer. I will be more careful with my IDE settings, for the tabs/space difference. 
Will your settings refactoring affect the branch 1.7 ? As I’m working with an older version of Stash I can’t test my code on the newest branches you made.

**Comment by SuperTux88** [comment]
Oh, didn't see this PR is for an older branch. My refactoring is for the latest version.

**Comment by pragbits** [comment]
Sorry, not accepting new feature in the old branch, only bug fix. Please add your PR to the latest master branch.

**Comment by pragbits** [comment]
NOTE: I've manually added your changes to the master branch (see this: https://github.com/pragbits/stash2slack/commit/c617bfef6ca50205eadffb0f13ee3505f23c1fd0)

**Comment by pragbits** [comment]
(However, it seems not working yet, still working on it)

**Comment by mrik974** [comment]
Thank you. I couldn't work on your latest branch since I don't work on the latest bit bucket server. I can still be here for help if you need. 

Emeric LEBON
06 84 85 15 72
Envoyé de mon iPhone

**Comment by mrik974** [comment]
If you have a runtime exception consider adding default parameters on deserialization. I had a hard time understanding that part. 

Emeric LEBON
06 84 85 15 72
Envoyé de mon iPhone

**Comment by pragbits** [comment]
It is not that. It simply not showing the emoji and image if I add them to the payload.

Example: 

{
	"text": "Test post", 
	"channel": "#test01", 
	"username": "test-bot", 
	"icon_url": "https://slack.com/img/icons/app-57.png",
	"icon_emoji": ":monkey_face:"
}

**Comment by mrik974** [comment]
The Emoji icon must be a Slack compatible code, not the emoji itself. Like :slack:
Sorry for not having documented this part enough.

**Comment by pragbits** [comment]
Does not matter, still not working:

```
{
	"text": "Test post", 
	"channel": "#test01", 
	"username": "test-bot", 
	"icon_url": "https://slack.com/img/icons/app-57.png",
	"icon_emoji": ":slack:"
}
```

**Comment by mrik974** [comment]
If they are correctly sent in json, Slack should accept these parameters. I use a custom icon url  (https://cdn1.iconfinder.com/data/icons/simple-icons/4096/bitbucket-4096-black.png) and a custom emoji I’ve created from it, and it’s working for me. 

I haven’t changed the code since my pull request, so I don’t know what the problem can be. Does the username work at least ?

**Comment by SuperTux88** [comment]
I think this is the Icon that is used as avatar for the bot, you can configure this also in slack. And in slack you can set an Image OR an Emoji, so I don't know what happens when you set both.

Also since this is the avatar for the bot for Bitbucket you should not use the slack-icon (https://slack.com/img/icons/app-57.png) as default, because I think it would override the settings configured in slack (not tested this) and then its weird when the bitbucket bot has a slack icon by default.

**Comment by dszabo** [comment]
The user name works. I don't get back the emoji nor the custom image displayed in the slack client (I am using Mac OS X slack client)

**Comment by dszabo** [comment]
Anyway, slack seems to accept the parameters, I just don't see it in the client at all when I tried to verify. Maybe it is an issue on my end but I don't understand what is the problem

**Comment by mrik974** [comment]
If Slack correctly receives them, then it's effectively a problem with your client. Which is weird, because I also use the Mac OS client, and it's only an integrated webview of their website...

Emeric LEBON
06 84 85 15 72
Envoyé de mon iPhone

**Comment by mrik974** [comment]
OK, I didn’t get that part. You are right, the emoji may not be useful. I set up the default slack icon because I didn’t know if I had the right to put the official bitbucket one :).

**Comment by SuperTux88** [comment]
What happens when you use an empty string as default (for url and emoji)? Does it use the the icon configured in slack? Or maybe only send the icon to slack if its configured? I think the default should be that it uses the icon that is configured in slack.

**Comment by pragbits** [comment]
You can try this release out: https://github.com/pragbits/stash2slack/releases/tag/2.0.2

Note that I could not verify the emoji nor the icon url, it is simply not working for me.

**Comment by mrik974** [comment]
I’m sorry, I can’t try it out. We don’t run the latest version of Stash, we can only work on the version for which I made the pull request :(.

**Comment by SuperTux88** [comment]
@mrik974 you can use the Atlassian Plugin SDK to test the plugin with the latest version :)

**Pull request closed without merging**
